version: '2.1'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfiles/php/Dockerfile
#    image: 9wimu9/vehicle-api-myapp
    ports:
      - '8003:8000'
    volumes:
      - './:/app'


#vehic-LoadB-DD7UYMPF8NH7-a3b45740b59b4abf.elb.us-east-1.amazonaws.com:8000
#        #https://github.com/aws/aws-cli/issues/6242#issuecomment-1079214960
#      aws ecs update-service --cluster vehicle-api --service vehicle-api-MyappService-buC4nKJtJY3G --region us-east-1 --enable-execute-command --force-new-deployment
#    aws ecs execute-command  \
#    --region us-east-1 \
#    --cluster vehicle-api \
#    --task b2b0c0c8236841f2b6800f8da45b3bb8 \
#    --container  myapp \
#    --command "/bin/bash" \
#    --interactive



