version: '2.1'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfiles/php/Dockerfile
    image: 9wimu9/api-gateway-laravel:latest
    ports:
      - '8000:8000'
#    volumes:
#      - './:/app'

#api-g-LoadB-5R1T98KT7U39-fbd70cb944acad73.elb.us-east-1.amazonaws.com:8000
#        #https://github.com/aws/aws-cli/issues/6242#issuecomment-1079214960
#      aws ecs update-service --cluster api-gateway --service api-gateway-MyappService-XSUKw431TYan --region us-east-1 --enable-execute-command --force-new-deployment
#    aws ecs execute-command  \
#    --region us-east-1 \
#    --cluster api-gateway \
#    --task c31b083789244c23bd4ab58c8f7f90d3 \
#    --container  laravel \
#    --command "/bin/bash" \
#    --interactive



