version: '2.1'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfiles/php/Dockerfile
    image: 9wimu9/api-gateway-myapp:latest
    ports:
      - '8003:8000'
#    volumes:
#      - './:/app'

#api-g-LoadB-1TAJT39MB1EHS-f67887059b6ed60c.elb.us-east-1.amazonaws.com:8000
#        #https://github.com/aws/aws-cli/issues/6242#issuecomment-1079214960
#      aws ecs update-service --cluster api-gateway --service api-gateway-MyappService-XSUKw431TYan --region us-east-1 --enable-execute-command --force-new-deployment
#    aws ecs execute-command  \
#    --region us-east-1 \
#    --cluster api-gateway \
#    --task 7c08025ff8cb4aa29e4e02580615ca1c \
#    --container  myapp \
#    --command "/bin/bash" \
#    --interactive



